# Electric and Magnetic fields for the Planeterrella simulation
import numpy as np
from abc import ABC, abstractmethod
from src.geometry import Planeterrella, Dipole, Sphere, Needle
from rich.progress import Progress, TextColumn, BarColumn, TimeRemainingColumn, MofNCompleteColumn
import os 
import json
import hashlib

_EPS0 = 8.854187817e-12  # Permittivity of free space, F/m
_CACHE_DIR = "field_cache/"  # Path to the cache file for electric field values

def _toJSON(value):
    """ json can't handle numpy arrays, so we give it a lil help"""
    match value:
        case np.ndarray():
            return [_toJSON(v) for v in value.tolist()]
        case _:
            return value

class Fields(ABC):
    @abstractmethod
    def at(self, position: np.ndarray) -> np.ndarray:
        pass

class MagneticField(Fields):
    # Magnetics field generated by the dipoles in the Planeterrella setup.
    def __init__(self, planeterrella: Planeterrella):
        self.dipoles: list[Dipole] = planeterrella.dipoles

    def at(self, positions: np.ndarray) -> np.ndarray:
        """
        Calculate the magnetic field at given positions.
        Parameters
        ----------
        Position : (N,3) ndarray

        Returns
        -------
        B : (N,3) ndarray
        """
        B = np.zeros_like(positions)

        for dipole in self.dipoles:
            r = positions-dipole.position    #(N,3)
            r_norm = np.linalg.norm(r, axis=1)  #(N,)
            m = dipole.moment * dipole.direction    #(3,)
            m_dot_r = r @ m  #(N,)
            mu_0 = 1.25663706212e-6  # T*m/A
            B += mu_0/(4*np.pi) * (3*r*(m_dot_r[:, None])/r_norm[:, None]**5 - m/r_norm[:, None]**3)
        return B

class ElectricField(Fields):
    # Electric field generated by the cathode and anode in the Planeterrella setup. No influence of the electrons. Assumes 2 points charges for simplicity.
    def __init__(self, planeterrella: Planeterrella, voltage: float):
        self.cathode = planeterrella.cathode
        self.anode = planeterrella.anode
        self.voltage = voltage

        if isinstance(self.cathode, Sphere) and isinstance(self.anode, Sphere):     # 2 sheres configuration
            R1 = self.cathode.radius
            R2 = self.anode.radius
            d = np.linalg.norm(self.anode.position - self.cathode.position)
            V = self.voltage
            Q = 4 * np.pi * _EPS0 * V / (1/R1 - 1/R2 + 2/d)

        else:       # 1 shere and 1 needle configuration
            if isinstance(self.cathode, Needle):
                needle = self.cathode
            else:
                needle = self.anode
            L = needle.lc + needle.lb
            R = needle.r
            V = self.voltage

            Q = 2 * np.pi * _EPS0 * V * L / np.log(2 * L / R)

        self.Q = Q


    def at(self, positions:np.ndarray) -> np.ndarray:
        """
        Calculate the electric field at given positions.
        Parameters
        ----------
        Position : (N,3) ndarray

        Returns
        -------
        E : (N,3) ndarray
        """
        # For simplicity, we assume a uniform electric field between the cathode and anode.
        # This is a simplification and may not represent the actual field distribution.
        k= 1/(4*np.pi*_EPS0)

        Q = self.Q
        # charges ponctuelles
        pos1 = self.cathode.position
        pos2 = self.anode.position
        r1 = positions - pos1  #(N,3)
        r2 = positions - pos2  #(N,3)
        n1, n2 = np.linalg.norm(r1, axis=1), np.linalg.norm(r2, axis=1)  #(N,)
        E = k * Q * (r1/n1[:,None]**3 - r2/n2[:,None]**3)  #(N,3)
        return E


class ElectricFieldv2(Fields):
    # Better electric field that considers the whle  surface of the electrodes.
    def __init__(self, planeterrella: Planeterrella, voltage: float, resolution: float = 0.005, use_cache: bool = True):
        """ resolution is in meters, and is the distance between the points of the grid. """
        self.cathode = planeterrella.cathode
        self.anode = planeterrella.anode
        self.dome = planeterrella.dome
        self.voltage = voltage
        self.resolution = resolution

        cache_path, params_json = None, None

        if use_cache:
            cache_path, params_json = self._cache_key()     #what key to expect for our current setup
            if os.path.exists(cache_path) and  self._load_cache(cache_path, params_json):       # check if already computed
                print(f"recovered previous E field from cache: {cache_path}")
                return
        with Progress(
                    TextColumn("[bold blue]{task.description}"),
                    BarColumn(),
                    TimeRemainingColumn(),
                    MofNCompleteColumn(),
                    transient=True
                    ) as progress:
            task = progress.add_task("[green]Computing E-field")
            self._build_grid()
            self._voxelize_electrodes()
            self._solve_laplace(tol=1e-5, maxiter=10000, progress=progress, task=task)
            self._build_interpolation(progress=progress, task=task)
        if use_cache:
            self._save_cache(cache_path, params_json)       #saving the computed E field to cache for future use
            print(f"saved E field to cache: {cache_path}")

    def at(self, positions: np.ndarray) -> np.ndarray:
        """
        Calculate the electric field at given positions.
        Parameters
        ----------
        Position : (N,3) ndarray

        Returns
        -------
        E : (N,3) ndarray
        """
        Ex = self._interp_Ex(positions)
        Ey = self._interp_Ey(positions)
        Ez = self._interp_Ez(positions)
        E = np.stack((Ex, Ey, Ez), axis=1)  # (N,3)
        return E

    def _load_cache(self, save_path: str, params_json: str) -> bool:
        """ loads the E field from cache if it exists and matches the current parameters."""
        try:
            data = np.load(save_path)
            if str(data['params_json']) != params_json:
                return False
            self.x = data['x']
            self.y = data['y']
            self.z = data['z']
            self.phi = data['phi_normalized'] * self.voltage  # scale back to actual voltage
            self.nx, self.ny, self.nz = data['nx'], data['ny'], data['nz']
            self.resX, self.resY, self.resZ = data['resX'], data['resY'], data['resZ']
            self._build_interpolation()
            return True
        except Exception as e:
            print(f"Failed to load E field cache: {e}. Recomputing from scratch.")
            return False
        
    def _save_cache(self, save_path, params_json: str):
        """ saves the E field to cache for future use."""

        phi_normalized = self.phi / self.voltage  # normalize to unit potential for linearity
        np.savez(save_path, 
                 x=self.x, y=self.y, z=self.z, phi_normalized=phi_normalized,
                 nx=self.nx, ny=self.ny, nz=self.nz,
                 resX=self.resX, resY=self.resY, resZ=self.resZ,
                 params_json=params_json)

    def _cache_key(self):
        """ generates a unique key for the current setup based on relevant parameters."""
        def electrode_signature(electrode):
            if isinstance(electrode, Sphere):
                return {
                    "type": "Sphere",
                    "radius": electrode.radius,
                    "position": electrode.position.tolist(),
                }
            elif isinstance(electrode, Needle):
                return {
                    "type": "Needle",
                    "position": electrode.position.tolist(),
                    "direction_vector": electrode.direction_vector.tolist(),
                    "length_cone": electrode.lb,
                    "length_cylinder": electrode.lc,
                    "radius": electrode.r
                }
            else:
                raise ValueError("Unknown electrode type")
        params = {
            "resolution": self.resolution,
            "dome": {"radius": self.dome.radius, "height": self.dome.height},
            "cathode": electrode_signature(self.cathode),
            "anode": electrode_signature(self.anode)
        }
        params_json = json.dumps(params, sort_keys=True)    #saving the relevant parameters to a json string 
        key = hashlib.sha256(params_json.encode("utf-8")).hexdigest()[:16]   # unique hash of the parameters to use as a cache key
        os.makedirs(_CACHE_DIR, exist_ok=True)
        return os.path.join(_CACHE_DIR, f"Efield_{key}.npz"), params_json
        
    def _build_grid(self):
        """ creates the grid with the given resolution and the size of the dome. """
        R, H = self.dome.radius, self.dome.height
        res = self.resolution
        nx = int( 2*R/res ) + 1
        ny = nx
        nz = int( H/res ) + 1
        self.x = np.linspace(-R, R, nx)
        self.y = np.linspace(-R, R, ny)
        self.z = np.linspace(0, H, nz)
        self.nx, self.ny, self.nz = nx, ny, nz
        self.resX = self.x[1] - self.x[0]
        self.resY = self.y[1] - self.y[0]
        self.resZ = self.z[1] - self.z[0]

    def _voxelize_electrodes(self):
        """ finds the points inside the cathode and anode spheres and sets their potential. Also fixes the points outside the dome to 0 potential. """
        X, Y, Z = np.meshgrid(self.x, self.y, self.z, indexing='ij')    # grid of points in the dome
        points = np.stack((X.ravel(), Y.ravel(), Z.ravel()), axis=1)  # list of the points coords (N,3)
        N = points.shape[0]
        fixed_mask = np.zeros(N, dtype=bool)        #fixed potential (outisde of domaine or electrod surfaces) for Dirichlet boundary conditions
        fixed_value = np.zeros(N, dtype=float)      #fixed potential associated to these points

        # dome is an insulator, zero flux
        excluded_mask = (points[:,0]**2 + points[:,1]**2 >= self.dome.radius**2) | (points[:,2] >= self.dome.height) | (points[:,2] <= 0) #outside of the dome

        def voxelize_needle(needle: Needle, potential: float):
            """ finds the points inside the needle and sets their potential. """
            axis = needle.direction_vector / np.linalg.norm(needle.direction_vector)  # unit vector along the needle axis
            relative_positions = points - needle.position  # (N,3)
            s = relative_positions @ axis  # (N,) projection of the points onto the needle axis
            perpendicular = relative_positions - np.outer(s, axis)  # (N,3) vector from the points to the needle axis
            perpendicular_distance = np.linalg.norm(perpendicular, axis=1)  # (N,) distance from the points to the needle axis
            in_cylinder = (s >= 0) & (s <= needle.lc) & (perpendicular_distance <= needle.r)  # points inside the cylinder
            in_cone = (s > needle.lc) & (s <= needle.lc + needle.lb) & (perpendicular_distance <= needle.r * (1 - (s - needle.lc) / needle.lb))  # points inside the cone
            inside = in_cylinder | in_cone
            fixed_mask[inside] = True
            fixed_value[inside] = potential

        def voxelize_sphere(sphere: Sphere, potential: float):
            """ finds the points inside the sphere and sets their potential. """
            position = sphere.position
            radius = sphere.radius
            distance = np.sum( (points - position)**2, axis=1 )
            inside = distance <= radius**2
            fixed_mask[inside] = True
            fixed_value[inside] = potential

        # anode
        (voxelize_sphere if isinstance(self.anode, Sphere) else voxelize_needle)(self.anode, self.voltage)       
        # cathode
        (voxelize_sphere if isinstance(self.cathode, Sphere) else voxelize_needle)(self.cathode, 0.0)       

        self.fixed_mask = fixed_mask
        self.fixed_value = fixed_value/ self.voltage  # normalize to unit potential for linearity
        self.excluded_mask = excluded_mask

    def _idx(self, i, j, k):
        return (i * self.ny + j) * self.nz + k

    def _solve_laplace(self, tol, maxiter, progress, task):
        import scipy.sparse as sp
        from scipy.sparse.linalg import cg
        """ solves the laplace equation with the fixed potential points. """
        # du2/dx2 + du2/dy2 + du2/dz2 = 0, U is the potential, with fixed boundary conditions (Dirichlet) on the electrodes and outside the dome.
        progress.update(task, description="[green]Solving Laplace equation")
        nx, ny, nz = self.nx, self.ny, self.nz
        dx2, dy2, dz2 = self.resX**2, self.resY**2, self.resZ**2

        I, J, K = np.meshgrid(np.arange(nx), np.arange(ny), np.arange(nz), indexing='ij')
        idx = self._idx(I, J, K).ravel()

        free = ~self.fixed_mask & ~self.excluded_mask
        solved_id = -np.ones(nx * ny * nz, dtype=np.int64)
        M = int(free.sum())
        solved_id[idx[free]] = np.arange(M)

        fi, fj, fk = I.ravel()[free], J.ravel()[free], K.ravel()[free]
        center_full = idx[free]
        center_solved = solved_id[center_full]


        rows = []
        cols = []
        data = []
        diag = np.zeros(M)
        b = np.zeros(M)

        # Standard Dirichlet-elimination FD assembly: fixed neighbors move to the
        # RHS instead of coupling into the matrix, which keeps A symmetric
        # positive-definite (required for CG to converge reliably).
        for di, dj, dk, h2 in [(1, 0, 0, dx2), (-1, 0, 0, dx2), (0, 1, 0, dy2), (0, -1, 0, dy2), (0, 0, 1, dz2), (0, 0, -1, dz2)]:
            ni = fi + di
            nj = fj + dj
            nk = fk + dk
            # in_bounds = (0 <= ni) & (ni < nx) & (0 <= nj) & (nj < ny) & (0 <= nk) & (nk < nz)
            # if not np.any(in_bounds):
            #     continue

            nb_full = self._idx(ni, nj, nk)
            included = ~self.excluded_mask[nb_full]

            diag[included] -= 1 / h2

            nb_solved = solved_id[nb_full]
            is_free_nb = (nb_solved) >= 0 & included
            rows.append(center_solved[is_free_nb])
            cols.append(nb_solved[is_free_nb])
            data.append(np.full(is_free_nb.sum(), 1 / h2))

            is_fixed_nb = self.fixed_mask[nb_full] & included
            np.add.at(b, center_solved[is_fixed_nb], -(1 / h2) * self.fixed_value[nb_full[is_fixed_nb]])
            

        rows.append(center_solved)
        cols.append(center_solved)
        data.append(diag)  

        rows = np.concatenate(rows)
        cols = np.concatenate(cols)
        data = np.concatenate(data)
        A = sp.csr_matrix((data, (rows, cols)), shape=(M, M))
        progress.update(task, description="[green]Performing conjugate gradient solve", total = maxiter, completed = 0)
        def callback(xk):
            progress.update(task, advance=1)
        phi_free, info = cg(A, b, rtol=tol, maxiter=maxiter, callback=callback)
        if info != 0:
            print(f"Warning: E-field solve did not fully converge (info={info}).")

        phi = np.zeros(nx * ny * nz)
        phi[idx[self.fixed_mask]] = self.fixed_value[self.fixed_mask]
        phi[idx[free]] = phi_free
        # excluded (outside-dome) cells are left at 0 -- not physically meaningful,
        # never sampled by `at()` for particle positions inside the dome anyway.
        self.phi = phi.reshape(nx, ny, nz)
        progress.update(task, advance=1) 

    def _build_interpolation(self, progress = None, task = None):
        """ builds an interpolation function for the potential. """
        from scipy.interpolate import RegularGridInterpolator
        dphidx, dphidy, dphidz = np.gradient(self.phi, self.resX, self.resY, self.resZ)
        Ex, Ey, Ez = -dphidx, -dphidy, -dphidz
        if progress is not None : progress.update(task, description="[green]Building interpolation functions")

        self._interp_Ex = RegularGridInterpolator((self.x, self.y, self.z), Ex, bounds_error=False, fill_value=0.0)
        if progress is not None : progress.update(task, advance=1)
        self._interp_Ey = RegularGridInterpolator((self.x, self.y, self.z), Ey, bounds_error=False, fill_value=0.0)
        if progress is not None : progress.update(task, advance=1)
        self._interp_Ez = RegularGridInterpolator((self.x, self.y, self.z), Ez, bounds_error=False, fill_value=0.0)
        if progress is not None : progress.update(task, advance=1)
    